version: '2'

services:
 transmission:
  build:
     context: .
     dockerfile: Dockerfile
  image: haugene/rpi-transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/blackbox/torrents:/data
  env_file:
    - .env
  environment:
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.1.0/24

 sonarr:
   build:
     context: https://github.com/linuxserver/docker-sonarr-armhf.git
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - /dev/rtc:/dev/rtc:ro
     - /media/blackbox/sonarr/series:/tv
     - /media/blackbox/sonarr/config:/config
     - /media/blackbox/torrents/completed/:/data/completed
     - /media/blackbox/torrents/completed/:/downloads
   ports:
     - "8989:8989"
   environment:
     - PUID=0
     - PGID=0
   depends_on:
    - transmission

 ssh-to-docker-host:
   build:
     context: git@github.com:flackdl/rpi-docker-autossh.git
   restart: always
   env_file:
    - .env
   volumes:
    - $PWD/id_rsa:/id_rsa
   dns:
    - 8.8.8.8
    - 4.2.2.4

# # proxy to a bunch of public trackers
# jackett:
#   build:
#     context: rpi-docker-jackett/
#   volumes:
#     - /media/blackbox/jackett/config/:/config
#     - /media/blackbox/torrents/completed/:/downloads

 cron:
   build:
     context: rpi-docker-cron/
   restart: always
   env_file:
    - .env
   volumes:
    - $PWD/dns-update.sh:/etc/cron.hourly/dns-update.sh
    - /var/log
   dns:
    - 8.8.8.8
    - 4.2.2.4
   network_mode: "host"
