version: '2'

services:
 transmission:
  build:
     context: .
     dockerfile: Dockerfile.armhf
  image: haugene/rpi-transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp:/data
  env_file:
    - .env
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.1.0/24

 proxy:
  build:
     context: ./proxy
     dockerfile: Dockerfile.armhf
  image: haugene/rpi-transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - "8080:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro
