version: '2'

services:
 plex:
  image: lsioarmhf/plex
  restart: always
  network_mode: "host"
  ports:
    - "32400:32400"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /media/pi/blackhole/plex/:/config
    - /media/pi/blackhole/torrents/completed/:/data/movies
    - /media/pi/blackhole/torrents/completed/:/data/tvshows
  environment:
    - PUID=1000
    - PGID=1000

 transmission:
  build:
     context: .
     dockerfile: Dockerfile
  image: haugene/rpi-transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/pi/blackhole/torrents:/data
  env_file:
    - .env
  environment:
    - PUID=1000
    - PGID=1000
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.1.0/24

 transmission-proxy:
   build:
     context: ./proxy/
   restart: always
   links:
     - transmission
   ports:
     - "8080:8080"
   depends_on:
     - transmission

 sonarr:
   build:
     context: https://github.com/linuxserver/docker-sonarr-armhf.git
   restart: always
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - /dev/rtc:/dev/rtc:ro
     - /media/pi/blackhole/sonarr/series:/tv
     - /media/pi/blackhole/sonarr/config:/config
     - /media/pi/blackhole/torrents:/downloads
   ports:
     - "8989:8989"
   environment:
     - PUID=1000
     - PGID=1000
   depends_on:
    - transmission

 ssh-to-docker-host:
   build:
     context: rpi-docker-autossh/
   restart: always
   env_file:
    - .env
   volumes:
    - $PWD/id_rsa:/id_rsa
   dns:
    - 8.8.8.8
    - 4.2.2.4

 cron:
   build:
     context: rpi-docker-cron/
   restart: always
   env_file:
    - .env
   volumes:
    - $PWD/dns-update.sh:/etc/cron.hourly/dns-update
    - /var/log
   dns:
    - 8.8.8.8
    - 4.2.2.4
   network_mode: "host"
